version: '3.8'
services:
  car-rental:
    build:
      context: .
      dockerfile: Dockerfile
    image: car-rental:latest
    container_name: car-rental
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=default
